spring:
  application:
    name: security-service
  profiles:
    default: local
  datasource:
    url: jdbc:mysql://${SECURITY_DB_HOST:localhost}:${SECURITY_DB_PORT:3306}/${SECURITY_DB_NAME:mediapp_security}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SECURITY_DB_USERNAME:root}
    password: ${SECURITY_DB_PASSWORD:}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          time_zone: UTC
    defer-datasource-initialization: true
  jackson:
#    serialization:
#      WRITE_DATES_AS_TIMESTAMPS: false

server:
  port: 8081

security:
  jwt:
    issuer: https://mediapp.local/security
    access-token-ttl: PT15M
  bootstrap:
    admin:
      email: admin@mediapp.local
      password: ChangeMe123!
      roles: ADMIN

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    com.mediapp.security_service: DEBUG
    org.springframework.security: INFO

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    metadata-map:
      app-type: security-service

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://${SECURITY_DB_HOST:security-db}:${SECURITY_DB_PORT:3306}/${SECURITY_DB_NAME:mediapp_security}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SECURITY_DB_USERNAME:security_user}
    password: ${SECURITY_DB_PASSWORD:security_pass}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          time_zone: UTC

eureka:
  client:
    service-url:
      defaultZone: http://${DISCOVERY_SERVER_HOST:discovery-server}:${DISCOVERY_SERVER_PORT:8761}/eureka

logging:
  level:
    com.mediapp.security_service: INFO

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://${SECURITY_DB_HOST}/${SECURITY_DB_NAME}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SECURITY_DB_USERNAME}
    password: ${SECURITY_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          log.warnings: true
          time_zone: UTC

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized
      roles: ACTUATOR_ADMIN

security:
  bootstrap:
    admin:
      password: ${SECURITY_ADMIN_PASSWORD:ChangeMe123!}

logging:
  level:
    com.mediapp.security_service: WARN
