spring:
  application:
    name: doctor-service
  main:
    web-application-type: reactive
  r2dbc:
    url: ${DOCTOR_SERVICE_R2DBC_URL:r2dbc:mysql://localhost:3306/mediapp_doctor?createDatabaseIfNotExist=true&serverTimezone=UTC}
    username: ${DOCTOR_SERVICE_DB_USERNAME:root}
    password: ${DOCTOR_SERVICE_DB_PASSWORD:}
    pool:
      enabled: true
      initial-size: 5
      max-size: 20
  autoconfigure:
    exclude: com.mediapp.logging.LoggingAutoConfiguration

mediapp:
  auditing:
    enabled: false

server:
  port: 0

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    com.mediapp.doctor_service: INFO
